services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/cinema_db
      - SECRET_KEY=your_jwt_secret_key_123
      - ENVIRONMENT=development
    volumes:
      - ./src:/app/src
      - ./src/logs:/app/src/logs
    networks:
      - cinema-network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  cinema-network:
    driver: bridge