"""Check for migration

Revision ID: 2f2c5b866f34
Revises: 6a2090c5ddb5
Create Date: 2025-08-09 15:13:13.819606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2c5b866f34'
down_revision: Union[str, Sequence[str], None] = '6a2090c5ddb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE reservation
    ALTER COLUMN status TYPE status
    USING status::text::status
""")
    op.drop_constraint(op.f('reservation_user_id_fkey'),
                       'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_users_id'), table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index(op.f('ix_users_id'), 'user', ['id'], unique=False)
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key(op.f('reservation_user_id_fkey'), 'reservation', 'user', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reservation', 'status',
                    existing_type=sa.Enum(
                        'PENDING', 'CONFIRMED', 'CANCELED', name='status'),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=False)
    # ### end Alembic commands ###
