version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/cinema_db
      - SECRET_KEY=your_jwt_secret_key_123
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - cinema-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cinema_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinema-network

volumes:
  postgres_data:

networks:
  cinema-network:
    driver: bridge
